language: node_js
node_js:
  - node
services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE travis_ci_test;" -U postgres
after_success: npm run coverage
deploy:
  provider: heroku
  api_key:
    secure: 'ebaUYDsUj872tMOMu44WygayuTYgtA/VUFM2Nmp5i5iuJ7FCr55hQcHJIA1ThOa0G976eVJ4yr80mVX27T0skD5KAgt/cWuL4Ps4m+Kwi7co0COb1NHu366HGiiecB3/PdKndcjtRAfPMbpu5r05KVWB1KECQi/NKckLhgibjWm+fgmMcV68322nUVQaPEVDprNGvM3U9QB8wwLrkskIPlO6IHmzLhcRhKZnjoa3YSoZbtnrgI5oThaKm09G3sas5gezUugI2gvjlqqAQaJb+r4uT5aD1WPPJfJWZqtljEyJ9hJc0Rnetl43q+LZWOtrE9yfdk2KPK3S8LFReoGdJpCUBY7u2hWSdoqDRSPZ8I0uH06R33e6SWVhbxbm4lW7O6EcuMpP6j6MfsY4ypgLKjqKiNqOttrGgpMoHwKP3FlhBbwJYmZPct1PWu2L1Ivml+M4zziJ7TZV1yMmJnKguIDFp14J54pnetkMTblQPQI7wPYIsQdttlwrBPsGOHdTDfO/oFi0MW80IcWoBMxTSbOfhRMcFex5tSwk8Ttkh5Qf1K36BbpIYeOnqOweT1SAwQ9hFk4lI99lJNbtfesVhmw0gQnmGaayY1LWf9QMFruDqNSPKemRKS9AdbNL6JuXDomvV5HsiZMqVvRuVrgB8i8qP3H5X9zciMO2WyoghKU='

  app: sendit-parcelapi
  run:
    - heroku config:set DATABASE_URI='postgres://dcwtudfleuswnu:ae2e9bbfceeb2504837c22675aaa67328b9c3341fbda4e264122aad1443f4412@ec2-35-173-94-156.compute-1.amazonaws.com:5432/d5cknp45u4t5jc'
    - heroku config:set JWT_SECRET=testing-a-secret-to-the-app-138abacuauana89101-109187q-heths-hell
    - heroku config:set JWT_EXPIRES_IN=90d
  on:
    repo: mofe64/sendIt
    branch: master
  skip_cleanup: 'true'
