language: node_js
node_js:
  - node
services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE travis_ci_test;" -U postgres
deploy:
  provider: heroku
  api_key:
    secure: 'ZeE2o1qCZA5ZFlI28mq2IVutub2HqqAp49nLmPZ1bbvT5whNOxr0kJnb9raCBwMYfEBUqkjOrxzwkMr6+Zii0orSsOuoHfhcQAmJDZjfRAkyWfsu167Nr3XNnfex40x0AeBAK/Jtnp/M8h5XR2SHNF1g3Cg42GuhRJgUnSX1qVQ6kzoaTzaLPAcwpfUO11sz0m6r/ad1hNopMSgDwdPDNluCQyw+ucfPHKFwYUD/1F0ZZHEQsfBeHLxTKd/zkGRn6y6iVtPaomUUUxUos0Qc5oGqGjU3CPeSukYD1/Rdq5OfA9v0Fa/UHnRx6n7iXKF8GQx8C8QrJaS17M7fO6Ms+iol/OnyUzZu8UDZP87vKyuk86fw8jPQ4m7MizoWn8xFqqxrbOH15INAGn56xmsXjs7Wh138+/11qsJyrUPCMyjL01MuVPQHbbTc3llKWSvudMSp/Zu6tVRm2lKsP2SuHbku/IqTLSkz7baIW4Hj0aSWBvHCrk70RGvhwj9FMxHY9FarpBZOwV7WAOlY5xVwL7pCLuK3aiUN7RiTJRXAU1y6i8XRrPsg7nddZhguuiJIG6xvNWM/92g89DyzvAazG/N4pqaomkcFG2kr1AicuKjL886F/lxAt6PMEbqtXKjY6t9CRRpl6nffq07BzZcxfgSDu+UHkMSlJuQ74pBDK0E='
  app: sendIT-mofe
  run: 'heroku addons:create heroku-postgresql:hobby-dev'
after_success: npm run coverage
env:
  global:
    secure: qegP7ABTbJJILcBhI1BSFGEvbnMe2j2GNcBf4ko3ysETavuPJH4og1v+c4sGgp/bJQgqd3K/1a6a+gqhwr+EQksjmD3NK1OBJAPfxqvsOR4zhCPgWaS2GXQ37Glt2ZGlhSzDqtDYfPNHmwKd1Vhqi7OX5BDuGhTn6cdomO6jaJffHkzo59QiEUb4B7qwg/NoX68ImXTKNzBGQK5m/gUaYenVVVcyxxZOAfxOJQJW10QGYVyQwBScjNp/XQ6pD/f/eMB9iW/v4dMp8SmpdslOQpddH7X+fSkTalb327yv3aMMh0dsHw4FMSuXV1C63+CI+eZYhdV5uX2GNZNUUTOVCcxUk2VhaeIzCS7ULH4hJ6YFiozLqzmrbXu6mxlTPC6RPrlpcG8DYUss6qs3YyLOuBWRfbys6DB3cNyBQBlpGDHrWsRESZOSL0IS/+tPk7KeYMd4mvkVKJcNhVUumgHBTWvkgYRMNNWyd5garmYH1NRqtaAiZHZsbiZLVSGcQ02c7L0AL9zMkdWwtYXmAypme7jkvgKvbzGLraZfeZs0wjipJ4XLd3f51hHRCrrGi4wYg/yiwAKVoAoxW1hr+gxykekezCkRuNFHHVXgU0saGKToLWHS5BNyFPO/J0cq2+0MN1wON4vKAhrMQeG2Biv0vzUn8aPTrK+AYTQqcs/4qzw=
